apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: nginx
      protocol: TCP
      name: nginx
    - port: 9253
      targetPort: php-fpm-metrics
      protocol: TCP
      name: php-fpm-metrics
  selector:
    app: hello-world
